//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipement_hotel
    {
        public int hotel_id { get; set; }
        public int equipement_id { get; set; }
    }
}
