//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string rue1 { get; set; }
        public string rue2 { get; set; }
        public string cp { get; set; }
        public string ville { get; set; }
        public string telephone { get; set; }
        public string descourt { get; set; }
        public string deslong { get; set; }
        public Nullable<double> prix { get; set; }
        public string motpasse { get; set; }
    }
}
