//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritHotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bdd : DbContext
    {
        public Bdd()
            : base("name=Bdd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chambre> chambre { get; set; }
        public virtual DbSet<chambre_reservation> chambre_reservation { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<equipement> equipement { get; set; }
        public virtual DbSet<equipement_hotel> equipement_hotel { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<photo> photo { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
    }
}
