//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritHotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bdd : DbContext
    {
        public Bdd()
            : base("name=Bdd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chambre> chambres { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<equipement> equipements { get; set; }
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
    }
}
